version: '3.7'

services:

  api-gateway:
    container_name: api-gateway
    image: ibm-cloud-academy/api-gateway:v1
    restart: always
    ports:
      - "8080:8080"
    networks:
      - back-tier

  service-registry:
    container_name: service-registry
    image: ibm-cloud-academy/service-registry:v1
    restart: always
    ports:
      - "8761:8761"
    networks:
      - back-tier

  hystrix-dashboard:
    container_name: hystrix-dashboard
    image: ibm-cloud-academy/hystrix-dashboard:v1
    restart: always
    ports:
      - "7979:7979"
    networks:
      - back-tier

  ibm-service:
    image: ibm-cloud-academy/ibm-service:v1
    restart: always
    networks:
      - back-tier
      
  cloud-service:
    image: ibm-cloud-academy/cloud-service:v1
    restart: always
    networks:
      - back-tier
      
  academy-service:
    image: ibm-cloud-academy/academy-service:v1
    restart: always
    networks:
      - back-tier
      
  mese-service:
    image: ibm-cloud-academy/mese-service:v1
    restart: always
    networks:
      - back-tier
      
networks:
  back-tier:
